### ISSUE TITLE
change sha1 to sha256

### ISSUE THREAD

**Issue by wesk1** [YingchunLi/ddwrt-certificate-admin#44]
3.4.0 version of openvpn in ios is complaining that ca signature hash algorithm is insecure to use a more secure, can this tools be update to use sha256 or something stronger instead of sha1 or whatever it's using to generate hash?

**Comment by YingchunLi** [comment]
Thanks for raising the issue. @wesk1 

Can you help to provide more details on:
1. how did you run the app in ios
2. what errors you got (like screenshots etc)
3. what is the result (Does the app breal? or the ca generated does not work?)
4. what is the expected resut

I will find time to take a look.

**Comment by wesk1** [comment]
I'm running the ios app in preferred(recommended)security level settings switching to insecure works but not recommended.

![image](https://github.com/YingchunLi/ddwrt-certificate-admin/assets/518983/1bae59bb-c4d5-424f-9f3d-935721060883)

the ca generated works fine but it's using sha1 instead of sha256 (assuming that's what the ios app is complaining about)

**Comment by wesk1** [comment]
i figure it out i ended up making changes to the x509.js file
